version: "3"
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - PORT=${NEST_PORT}
      - DOMAIN=${DOMAIN}
      - VUE_PORT=${VUE_PORT}
      - OAUTH2_UID=${OAUTH2_UID}
      - OAUTH2_SECRET=${OAUTH2_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - WEBSOCKET_PORT=${GAME_PORT}
    #restart: always
    command: npm run start:prod
    # command: npm run start:prod
    container_name: back
    volumes:
      - ./back/uploads:/uploads
    ports:
      - "${NEST_PORT}:4000"
      - "${GAME_PORT}:4001"
      - "${CHAT_PORT}:8082"
  database:
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ft_transcendence
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
    container_name: database
    ports:
      - "5432:5432"
  front:
    build:
      context: ./front
      dockerfile: Dockerfile_Prod
      args:
        - VUE_APP_PORT=${VUE_PORT}
        - VUE_APP_DOMAIN=${DOMAIN}
        - VUE_APP_OAUTH2_UID=${OAUTH2_UID}
        - VUE_APP_NEST_PORT=${NEST_PORT}
        - VUE_APP_GAME_PORT=${GAME_PORT}
        - VUE_APP_CHAT_PORT=${CHAT_PORT}
    restart: always
    container_name: front
    ports:
      - "${VUE_PORT}:80"
volumes:
  dbdata:
    driver: local
