version: "3"
services:
  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - NEST_PORT=${NEST_PORT}
      - DOMAIN=${DOMAIN}
      - URL=${URL}
      - VUE_PORT=${VUE_PORT}
      - OAUTH2_UID=${OAUTH2_UID}
      - OAUTH2_SECRET=${OAUTH2_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    #restart: always
    command: npm run start:prod
    # command: npm run start:prod
    volumes:
      - ./back/uploads:/uploads
      - ./ssl:/ssl
    ports:
      - "${NEST_PORT}:4000"
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: database
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ft_transcendence
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile_Prod
      args:
        - VUE_APP_PORT=${VUE_PORT}
        - VUE_APP_URL=${URL}
        - VUE_APP_DOMAIN=${DOMAIN}
        - VUE_APP_OAUTH2_UID=${OAUTH2_UID}
        - VUE_APP_NEST_PORT=${NEST_PORT}
    # restart: always
    ports:
      - "${VUE_PORT}:80"
volumes:
  dbdata:
    driver: local
