version: '3'
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    #restart: always
    command: npm run start:dev
    # command: npm run start:prod
    container_name: back
    ports:
      - "3000:3000"
  database:
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ft_transcendence
      POSTGRES_PASSWORD: password
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    container_name: database
    ports:
      - "5432:5432"
  front:
    build:
      context: ./front
      dockerfile: Dockerfile_Dev
    #restart: always
    command: vue ui --host 0.0.0.0 --port 8000 --headless # dev purpose
    #command: npm run serve
    container_name: front
    ports:
      - "8080:8080" # use 80 on production build
      - "8000:8000" # dev prupose
