FROM node:lts-alpine as build-stage

LABEL maintainer="Nicolas Foray <nforay@student.42.fr>"

WORKDIR /app
COPY ./vue-app-project/package*.json ./
RUN npm install -g @vue/cli && npm install --legacy-peer-deps
COPY ./vue-app-project/ .

ARG VUE_APP_PORT=${VUE_APP_PORT}
ARG VUE_APP_DOMAIN=${VUE_APP_DOMAIN}
ARG VUE_APP_OAUTH2_UID=${VUE_APP_OAUTH2_UID}
ARG VUE_APP_NEST_PORT=${VUE_APP_NEST_PORT}
ARG VUE_APP_GAME_PORT=${VUE_APP_GAME_PORT}
ARG VUE_APP_CHAT_PORT=${VUE_APP_CHAT_PORT}

RUN npm run build

FROM nginx as production-stage

EXPOSE 80

RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
