FROM node:lts-alpine as build-stage

MAINTAINER Nicolas Foray <nforay@student.42.fr>

RUN mkdir /app
ADD . /app
WORKDIR /app
RUN npm i -g @vue/cli
RUN cd vue-app-project && npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
