FROM node:lts-alpine as build-stage

LABEL maintainer="Nicolas Foray <nforay@student.42.fr>"

WORKDIR /app
COPY ./vue-app-project/package*.json ./
RUN npm install -g @vue/cli && npm install --legacy-peer-deps
COPY ./vue-app-project/ .
RUN npm run build

FROM nginx as production-stage

EXPOSE ${FRONTPORT}

RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
